import React from 'react';
import { 
  FileText, 
  Download, 
  Search, 
  Calendar, 
  ArrowRight, 
  PieChart as PieChartIcon, 
  TrendingUp, 
  Clock,
  ExternalLink
} from 'lucide-react';
import { Card } from '../../components/common/Card';
import { Button, Badge } from '../../components/common/Button';
import { Table } from '../../components/common/Table';

const Reports: React.FC = () => {
  const reportCategories = [
    { name: 'Financial Insights', count: 12, icon: TrendingUp, color: 'bg-blue-500' },
    { name: 'Bureau Statistics', count: 8, icon: PieChartIcon, color: 'bg-green-500' },
    { name: 'Upload Audits', count: 15, icon: Clock, color: 'bg-amber-500' },
    { name: 'Custom Exports', count: 4, icon: Download, color: 'bg-primary-600' },
  ];

  const recentReports = [
    { id: 'REP-001', name: 'Monthly Credit Trend - March 2026', type: 'PDF', generatedOn: '20 Mar 2026', size: '2.4 MB', user: 'Admin' },
    { id: 'REP-002', name: 'Default Customer List - Quarterly', type: 'CSV', generatedOn: '18 Mar 2026', size: '1.2 MB', user: 'Sid. V' },
    { id: 'REP-003', name: 'Bank-wise Performance Audit', type: 'PDF', generatedOn: '15 Mar 2026', size: '4.8 MB', user: 'Admin' },
    { id: 'REP-004', name: 'Identity Validation Summary', type: 'XLSX', generatedOn: '12 Mar 2026', size: '850 KB', user: 'Neha G' },
  ];

  const columns = [
    {
      header: 'Report Name',
      accessorKey: 'name',
      cell: (info: any) => (
        <div className="flex items-center">
          <FileText size={16} className="text-slate-400 mr-3 shrink-0" />
          <span className="font-bold text-slate-900 truncate max-w-[200px]">{info.getValue()}</span>
        </div>
      )
    },
    {
      header: 'Type',
      accessorKey: 'type',
      cell: (info: any) => (
        <Badge variant={info.getValue() === 'PDF' ? 'primary' : info.getValue() === 'CSV' ? 'success' : 'info'}>
          {info.getValue()}
        </Badge>
      )
    },
    { header: 'Generated On', accessorKey: 'generatedOn' },
    { header: 'Generated By', accessorKey: 'user' },
    {
      header: '',
      id: 'actions',
      cell: () => (
        <div className="flex items-center space-x-2">
          <Button variant="ghost" size="sm" leftIcon={<Download size={14} />}>
            Download
          </Button>
          <Button variant="ghost" size="sm">
            <ExternalLink size={14} />
          </Button>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 uppercase tracking-tight">Reports & Analytics</h1>
          <p className="text-slate-500 font-medium">Generate and export comprehensive bureau data reports.</p>
        </div>
        <div className="flex items-center">
          <Button variant="primary" leftIcon={<Calendar size={18} />}>
            New Custom Report
          </Button>
        </div>
      </div>

      {/* Categories Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {reportCategories.map((cat, idx) => (
          <Card key={idx} className="hover:border-primary-200 transition-all cursor-pointer group">
            <div className="flex items-center justify-between">
              <div className={`w-12 h-12 ${cat.color} rounded-2xl flex items-center justify-center text-white shadow-lg`}>
                <cat.icon size={24} />
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">{cat.name}</p>
                <p className="text-2xl font-black text-slate-900 mt-0.5">{cat.count}</p>
              </div>
            </div>
            <div className="mt-6 flex items-center text-primary-600 font-bold text-xs uppercase tracking-widest group-hover:translate-x-1 transition-transform">
              Explore Reports <ArrowRight size={14} className="ml-2" />
            </div>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Reports Table */}
        <div className="lg:col-span-2 space-y-6">
          <Card title="Recent Report History">
             <div className="flex items-center justify-between mb-4">
                <div className="relative w-full max-w-xs">
                  <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                  <input 
                    type="text" 
                    placeholder="Search reports..." 
                    className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg outline-none text-xs"
                  />
                </div>
                <Button variant="ghost" size="sm">View All</Button>
             </div>
             <div className="-mx-6">
                <Table columns={columns} data={recentReports} />
             </div>
          </Card>
        </div>

        {/* Templates/Quick Export */}
        <div className="space-y-6">
          <Card title="Quick Export Templates">
            <div className="space-y-3">
              {[
                { name: 'Full Database Snapshot', type: 'XLSX', time: '5m' },
                { name: 'Negative List (Blacklisted)', type: 'CSV', time: '1m' },
                { name: 'Bank Distribution Chart', type: 'PDF', time: '2m' },
                { name: 'Identity Audit Log', type: 'JSON', time: '10s' },
              ].map((template, idx) => (
                <div key={idx} className="p-4 bg-slate-50 border border-slate-100 rounded-xl hover:border-primary-200 hover:bg-white transition-all cursor-pointer group">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-sm font-bold text-slate-900">{template.name}</p>
                    <Badge variant="primary">{template.type}</Badge>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-slate-400 font-bold uppercase tracking-widest flex items-center">
                      <Clock size={12} className="mr-1.5" /> Est: {template.time}
                    </span>
                    <button className="text-primary-600 font-black text-[10px] uppercase tracking-widest opacity-0 group-hover:opacity-100 transition-opacity">
                      Generate Now
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <Card className="bg-primary-600 border-none text-white overflow-hidden relative">
            <div className="relative z-10">
              <h4 className="text-lg font-black uppercase tracking-tight mb-2">Schedule Reports</h4>
              <p className="text-sm text-primary-50 mb-6">Automate your reporting workflow with scheduled exports via email or SFTP.</p>
              <Button variant="secondary" className="w-full bg-white text-primary-600 hover:bg-primary-50 border-none font-black uppercase tracking-widest text-[11px]">Configure Automation</Button>
            </div>
            {/* Abstract Background Design */}
            <div className="absolute -right-8 -bottom-8 w-32 h-32 bg-white/10 rounded-full blur-2xl"></div>
            <div className="absolute -left-4 -top-4 w-24 h-24 bg-primary-400/20 rounded-full blur-xl"></div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Reports;
